### ISSUE TITLE
compatible issue under vite+vue project

### ISSUE THREAD

**Issue by lunaeidolon** [LuchoTurtle/tweakpane-plugin-file-import#73] opened 2024-06-16 19:10 UTC
the console says:

`_TpError {message: "Not compatible with  plugin 'undefined.file-input'", name: '_TpError', stack: "Error: Not compatible with  plugin 'undefined.file…ode_modules/.vite/deps/vue.js?v=55e2a4eb:9044:36)", type: 'notcompatible'}message: "Not compatible with  plugin 'undefined.file-input'"name: "_TpError"stack: "Error: Not compatible with  plugin 'undefined.file-input'\n    at new _TpError (http://10.0.0.64:5173/node_modules/.vite/deps/tweakpane.js?v=55e2a4eb:83:18)\n    at _TpError.notCompatible (http://10.0.0.64:5173/node_modules/.vite/deps/tweakpane.js?v=55e2a4eb:61:12)\n    at PluginPool.register (http://10.0.0.64:5173/node_modules/.vite/deps/tweakpane.js?v=55e2a4eb:6924:21)\n    at http://10.0.0.64:5173/node_modules/.vite/deps/tweakpane.js?v=55e2a4eb:7477:18\n    at Array.forEach (<anonymous>)\n    at Pane.registerPlugin (http://10.0.0.64:5173/node_modules/.vite/deps/tweakpane.js?v=55e2a4eb:7476:13)\n    at setup (http://10.0.0.64:5173/src/App.vue?t=1718564959498:24:6)\n    at callWithErrorHandling (http://10.0.0.64:5173/node_modules/.vite/deps/vue.js?v=55e2a4eb:1662:19)\n    at setupStatefulComponent (http://10.0.0.64:5173/node_modules/.vite/deps/vue.js?v=55e2a4eb:9083:25)\n    at setupComponent (http://10.0.0.64:5173/node_modules/.vite/deps/vue.js?v=55e2a4eb:9044:36)"type: "notcompatible"[[Prototype]]: Object
(anonymous) @ vue.js?v=55e2a4eb:2019
(anonymous) @ App.vue?t=1718564958825:123
(anonymous) @ client:34
(anonymous) @ client:218
(anonymous) @ client:193
queueUpdate @ client:193
await in queueUpdate (async)
(anonymous) @ client:638
handleMessage @ client:636
(anonymous) @ client:546
Show 1 more frame
Show less`

the code:

`<script setup>

import { ref } from "vue";
import { Pane } from "tweakpane";

import * as TweakpaneFileImportPlugin from "tweakpane-plugin-file-import";

const pane = new Pane();
pane.registerPlugin(TweakpaneFileImportPlugin);
</script>`

**Comment by LuchoTurtle** [comment] 2024-06-17 05:28
Thank you for opening an issue :)

Can you provide more insight (and maybe a reproducible example)? Version of Vue, `npm`, OS... That would help me narrow down the issue :)

**Comment by remorses** [comment] 2024-09-13 19:48
The problem is that the latest version on npm is the one compatible with tweakpane v3: https://www.npmjs.com/package/tweakpane-plugin-file-import/?activeTab=code

You have to manually install the correct version: `pnpm i tweakpane-plugin-file-import@1`

**Comment by LuchoTurtle** [comment] 2024-09-13 21:55
Thank you @remorses for the tip 😍 . I've released `v1.1.1` so the latest version is not from the `v0` branch (that supports `Tweakpane v3` only).

Closing this one. Thanks again!

**Closed by LuchoTurtle** 2024-09-13 21:55 UTC
